#!/usr/bin/env python3
"""
Generate a weekly digest summarizing activity over the past 7 days.
Creates a markdown file in /digests/ directory.
"""

import json
from datetime import datetime, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "data" / "index.json"
DIGESTS_DIR = REPO_ROOT / "digests"


def main():
    DIGESTS_DIR.mkdir(parents=True, exist_ok=True)

    if not DATA_FILE.exists():
        print("No data/index.json found. Run aggregate.py first.")
        return

    data = json.loads(DATA_FILE.read_text(encoding="utf-8"))

    today = datetime.now().date()
    week_ago = today - timedelta(days=7)
    week_str = f"{week_ago.isoformat()} to {today.isoformat()}"

    tasks = data.get("tasks", [])
    logs = data.get("logs", [])
    ideas = data.get("ideas", [])
    projects = data.get("projects", [])

    # Tasks completed this week
    completed = []
    created = []
    in_progress = []
    for t in tasks:
        updated = t.get("updated", t.get("created", ""))
        created_date = t.get("created", "")
        try:
            if t.get("status") == "done" and updated:
                d = datetime.strptime(updated, "%Y-%m-%d").date()
                if d >= week_ago:
                    completed.append(t)
            if created_date:
                d = datetime.strptime(created_date, "%Y-%m-%d").date()
                if d >= week_ago:
                    created.append(t)
        except ValueError:
            pass
        if t.get("status") == "in-progress":
            in_progress.append(t)

    # Logs this week
    weekly_logs = []
    for log in logs:
        try:
            d = datetime.strptime(log.get("date", ""), "%Y-%m-%d").date()
            if d >= week_ago:
                weekly_logs.append(log)
        except ValueError:
            pass

    # Ideas this week
    weekly_ideas = []
    for idea in ideas:
        try:
            d = datetime.strptime(idea.get("created", ""), "%Y-%m-%d").date()
            if d >= week_ago:
                weekly_ideas.append(idea)
        except ValueError:
            pass

    # Overdue tasks
    overdue = []
    for t in tasks:
        if t.get("status") == "done":
            continue
        due = t.get("due", "")
        if due:
            try:
                d = datetime.strptime(due, "%Y-%m-%d").date()
                if d < today:
                    overdue.append(t)
            except ValueError:
                pass

    # Build digest
    lines = [
        f"# Weekly Digest: {week_str}",
        f"",
        f"*Generated on {today.isoformat()}*",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Tasks Completed | {len(completed)} |",
        f"| Tasks Created | {len(created)} |",
        f"| Tasks In Progress | {len(in_progress)} |",
        f"| Log Entries | {len(weekly_logs)} |",
        f"| New Ideas | {len(weekly_ideas)} |",
        f"| Overdue Tasks | {len(overdue)} |",
        f"| Total Projects | {len(projects)} |",
        f"",
    ]

    if completed:
        lines.append("## Completed Tasks")
        lines.append("")
        for t in completed:
            lines.append(f"- **{t.get('title', t.get('id', 'untitled'))}** ({t.get('project', 'no project')})")
        lines.append("")

    if in_progress:
        lines.append("## In Progress")
        lines.append("")
        for t in in_progress:
            due_str = f" - due {t['due']}" if t.get("due") else ""
            lines.append(f"- {t.get('title', t.get('id', 'untitled'))} ({t.get('project', 'no project')}){due_str}")
        lines.append("")

    if overdue:
        lines.append("## Overdue")
        lines.append("")
        for t in overdue:
            lines.append(f"- **{t.get('title', t.get('id', ''))}** - due {t.get('due', '?')}")
        lines.append("")

    if weekly_logs:
        lines.append("## Log Entries")
        lines.append("")
        for log in sorted(weekly_logs, key=lambda l: l.get("date", ""), reverse=True):
            summary = log.get("body", "").split("\n")[0].replace("## Summary", "").strip()[:100]
            lines.append(f"- **{log.get('date', '?')}**: {summary}")
        lines.append("")

    if weekly_ideas:
        lines.append("## New Ideas")
        lines.append("")
        for idea in weekly_ideas:
            body = idea.get("body", "").split("\n")[0].replace("## Idea", "").strip()[:80]
            lines.append(f"- {body} ({', '.join(idea.get('tags', []))})")
        lines.append("")

    lines.append("---")
    lines.append(f"*Auto-generated by Life Long weekly digest*")

    digest_file = DIGESTS_DIR / f"digest-{today.isoformat()}.md"
    digest_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated digest: {digest_file}")


if __name__ == "__main__":
    main()
